-- 
DROP TABLE IF EXISTS t_tasks;
CREATE TABLE t_tasks (
	id BIGINT(20) not NULL auto_increment,
	name VARCHAR(50) NULL DEFAULT NULL,
	description VARCHAR(200) NULL DEFAULT NULL,
	developer VARCHAR(50) NULL DEFAULT NULL,
	status INT(1) NULL DEFAULT NULL,
	codesNum BIGINT(20) NULL DEFAULT NULL,
	planedStartDate TIMESTAMP NULL DEFAULT NULL,
	planedFinishDate TIMESTAMP NULL DEFAULT NULL,
	actualStartDate TIMESTAMP NULL DEFAULT NULL,
	actualFinishDate TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY  (id)
);
