-- 
DROP TABLE IF EXISTS t_tasks;
CREATE TABLE t_tasks (
	id BIGINT(20) not NULL auto_increment,
	name VARCHAR(50) NULL DEFAULT NULL,
	sn VARCHAR(50) NULL DEFAULT NULL,
	description VARCHAR(200) NULL DEFAULT NULL,
	developer VARCHAR(50) NULL DEFAULT NULL,
	status INT(1) NULL DEFAULT NULL,
	codesNum BIGINT(20) NULL DEFAULT NULL,
	createTime BIGINT(13) NULL DEFAULT NULL,
	updateTime BIGINT(13) NULL DEFAULT NULL,
	planedStartTime BIGINT(13) NULL DEFAULT NULL,
	planedFinishTime BIGINT(13) NULL DEFAULT NULL,
	actualStartTime BIGINT(13) NULL DEFAULT NULL,
	actualFinishTime BIGINT(13) NULL DEFAULT NULL,
	PRIMARY KEY  (id)
);
